export const chartTheme = {
    public: {
      borderWidth: 2,
      hoverRadius: 0,
      pointHitRadius: 0,
      pointHoverRadius: 6,
      pointRadius: 3,
      fill: false,
      lineTension: 0.5,
      pointHoverBorderWidth: 2,
      pointBorderWidth: 3,
    },
    e0: {
      label: "TP",
      // borderDash: [1, 1],
      pointStyle: false,
      backgroundColor: "rgba(0, 150, 0, 0.2)",
      borderColor: "rgb(0, 150, 0)",
      pointBackgroundColor: "rgb(0, 150, 0)",
      pointHoverBorderColor: "rgb(0, 150, 0)",
      pointHoverBackgroundColor: "rgb(0, 150, 0)",
    },
    e1: {
      label: "FN",
      borderDash: [1, 3],
      pointStyle: false,
      backgroundColor: "rgba(255, 0, 0, 0.2)",
      borderColor: "rgb(255, 0, 0)",
      pointBackgroundColor: "rgb(255, 0, 0)",
      pointHoverBorderColor: "rgb(255, 0, 0)",
      pointHoverBackgroundColor: "rgb(255, 0, 0)",
    },
    e2: {
      label: "FP",
      // borderDash: [1, 2],
      pointStyle: false,
      backgroundColor: "rgba(255, 0, 0, 0.2)",
      borderColor: "rgb(218, 3, 3)",
      pointBackgroundColor: "rgb(255, 0, 0)",
      pointHoverBorderColor: "rgb(255, 0, 0)",
      pointHoverBackgroundColor: "rgb(255, 0, 0)",
    },
    e3: {
      label: "TN",
      borderDash: [1, 3],
      pointStyle: false,
      backgroundColor: "rgba(0, 150, 0, 0.2)",
      borderColor: "rgb(0, 150, 0)",
      pointBackgroundColor: "rgb(0, 150, 0)",
      pointHoverBorderColor: "rgb(0, 150, 0)",
      pointHoverBackgroundColor: "rgb(0, 150, 0)",
    },
    e4: {
      label: "Label Positive",
      // borderDash: [1, 2],
      pointStyle: false,
      backgroundColor: "rgba(0, 162, 199, 0.2",
      borderColor: "rgb(0, 162, 199)",
      pointBackgroundColor: "rgb(0, 162, 199)",
      pointHoverBorderColor: "rgb(0, 162, 199)",
      pointHoverBackgroundColor: "rgb(0, 162, 199)",
    },
    e5: {
      label: "Label Negative",
      // borderDash: [1, 2],
      pointStyle: false,
      backgroundColor: "rgba(0, 162, 199, 0.2",
      borderColor: "rgb(0, 162, 199)",
      pointBackgroundColor: "rgb(0, 162, 199)",
      pointHoverBorderColor: "rgb(0, 162, 199)",
      pointHoverBackgroundColor: "rgb(0, 162, 199)",
    },
    e6: {
      label: "Prediction Positive",
      // borderDash: [1, 2],
      pointStyle: false,
      backgroundColor: "rgba(0, 162, 199, 0.2",
      borderColor: "rgb(0, 162, 199)",
      pointBackgroundColor: "rgb(0, 162, 199)",
      pointHoverBorderColor: "rgb(0, 162, 199)",
      pointHoverBackgroundColor: "rgb(0, 162, 199)",
    },
    e7: {
      label: "Prediction Negative",
      // borderDash: [1, 2],
      pointStyle: false,
      backgroundColor: "rgba(0, 162, 199, 0.2",
      borderColor: "rgb(0, 162, 199)",
      pointBackgroundColor: "rgb(0, 162, 199)",
      pointHoverBorderColor: "rgb(0, 162, 199)",
      pointHoverBackgroundColor: "rgb(0, 162, 199)",
    },
    e8: {
      label: "Accuracy",
      pointStyle: true,
      backgroundColor: "rgba(0, 0, 0, 0.1)",
      borderColor: "rgba(0, 0, 0, 0.7)",
      pointBackgroundColor: "rgba(0, 0, 0, 0.7)",
      pointHoverBorderColor: "rgba(0, 0, 0, 0.7)",
      pointHoverBackgroundColor: "rgba(0, 0, 0, 0.7)",
    },
    numsNH: {
      label: "numsNH",
      pointStyle: false,
      backgroundColor: "rgba(0, 0, 0, 0.1)",
      borderColor: "rgb(255, 70, 70)",
      pointBackgroundColor: "rgba(0, 0, 0, 0.7)",
      pointHoverBorderColor: "rgba(0, 0, 0, 0.7)",
      pointHoverBackgroundColor: "rgba(0, 0, 0, 0.7)",
    },
    numsH: {
      label: "numsH",
      pointStyle: false,
      backgroundColor: "rgba(0, 0, 0, 0.1)",
      borderColor: "rgb(70, 140, 255)",
      pointBackgroundColor: "rgba(0, 0, 0, 0.7)",
      pointHoverBorderColor: "rgba(0, 0, 0, 0.7)",
      pointHoverBackgroundColor: "rgba(0, 0, 0, 0.7)",
    },





    
    e0_ideal: {
      label: "TP_ideal",
      // hoverRadius: 5,
      // pointBorderWidth: 5,
      // borderDash: [1, 1],
      pointStyle: false,
      backgroundColor: "rgba(0, 150, 0, 0.2)",
      borderColor: "rgb(0, 150, 0)",
      pointBackgroundColor: "rgb(0, 150, 0)",
      pointHoverBorderColor: "rgb(0, 150, 0)",
      pointHoverBackgroundColor: "rgb(0, 150, 0)",
    },
    e1_ideal: {
      label: "FN_ideal",
      // hoverRadius: 5,
      // pointBorderWidth: 5,
      borderDash: [1],
      pointStyle: false,
      backgroundColor: "rgba(255, 0, 0, 0.2)",
      borderColor: "rgb(255, 0, 0)",
      pointBackgroundColor: "rgb(255, 0, 0)",
      pointHoverBorderColor: "rgb(255, 0, 0)",
      pointHoverBackgroundColor: "rgb(255, 0, 0)",
    },
    e2_ideal: {
      label: "FP_ideal",
      // hoverRadius: 5,
      // pointBorderWidth: 5,
      // borderDash: [1, 2],
      pointStyle: false,
      backgroundColor: "rgba(255, 0, 0, 0.2)",
      borderColor: "rgb(218, 3, 3)",
      pointBackgroundColor: "rgb(255, 0, 0)",
      pointHoverBorderColor: "rgb(255, 0, 0)",
      pointHoverBackgroundColor: "rgb(255, 0, 0)",
    },
    e3_ideal: {
      label: "TN_ideal",
      // hoverRadius: 5,
      // pointBorderWidth: 5,
      borderDash: [1, 1],
      pointStyle: false,
      backgroundColor: "rgba(0, 150, 0, 0.2)",
      borderColor: "rgb(0, 150, 0)",
      pointBackgroundColor: "rgb(0, 150, 0)",
      pointHoverBorderColor: "rgb(0, 150, 0)",
      pointHoverBackgroundColor: "rgb(0, 150, 0)",
    },
    e4_ideal: {
      label: "Label Positive_ideal",
      // hoverRadius: 5,
      // pointBorderWidth: 5,
      // borderDash: [1, 2],
      pointStyle: false,
      backgroundColor: "rgba(0, 162, 199, 0.2",
      borderColor: "rgb(0, 162, 199)",
      pointBackgroundColor: "rgb(0, 162, 199)",
      pointHoverBorderColor: "rgb(0, 162, 199)",
      pointHoverBackgroundColor: "rgb(0, 162, 199)",
    },
    e5_ideal: {
      label: "Label Negative_ideal",
      // hoverRadius: 5,
      // pointBorderWidth: 5,
      // borderDash: [1, 2],
      pointStyle: false,
      backgroundColor: "rgba(0, 162, 199, 0.2",
      borderColor: "rgb(0, 162, 199)",
      pointBackgroundColor: "rgb(0, 162, 199)",
      pointHoverBorderColor: "rgb(0, 162, 199)",
      pointHoverBackgroundColor: "rgb(0, 162, 199)",
    },
    e6_ideal: {
      label: "Prediction Positive_ideal",
      // hoverRadius: 5,
      // pointBorderWidth: 5,
      // borderDash: [1, 2],
      pointStyle: false,
      backgroundColor: "rgba(0, 162, 199, 0.2",
      borderColor: "rgb(0, 162, 199)",
      pointBackgroundColor: "rgb(0, 162, 199)",
      pointHoverBorderColor: "rgb(0, 162, 199)",
      pointHoverBackgroundColor: "rgb(0, 162, 199)",
    },
    e7_ideal: {
      label: "Prediction Negative_ideal",
      // hoverRadius: 5,
      // pointBorderWidth: 5,
      // borderDash: [1, 2],
      pointStyle: false,
      backgroundColor: "rgba(0, 162, 199, 0.2",
      borderColor: "rgb(0, 162, 199)",
      pointBackgroundColor: "rgb(0, 162, 199)",
      pointHoverBorderColor: "rgb(0, 162, 199)",
      pointHoverBackgroundColor: "rgb(0, 162, 199)",
    },
    e8_ideal: {
      label: "Accuracy_ideal",
      // hoverRadius: 5,
      // pointBorderWidth: 5,
      pointStyle: true,
      backgroundColor: "rgba(0, 0, 0, 0.1)",
      borderColor: "rgba(0, 0, 0, 0.7)",
      pointBackgroundColor: "rgba(0, 0, 0, 0.7)",
      pointHoverBorderColor: "rgba(0, 0, 0, 0.7)",
      pointHoverBackgroundColor: "rgba(0, 0, 0, 0.7)",
    },
  }